server:
  port: 4004

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
          # Route for /api/patients/** to patient-service
          ## REST CLIENT -> http://localhost:4004/api/patients
          ## API GATEWAY -> http://patient-service:4000/patients
          ## PATIENT SERVICE (SPRING BOOT APP) -> /patients -> Patients array
          - id: patient-service-route
            uri: http://patient-service:4000
            predicates:
              - Path=/api/patients/**
            filters:
              - StripPrefix=1
          # Route for /api/docs/patients to patient-service /v3/api-docs
          ## REST CLIENT -> http://localhost:4004/api-docs/patients
          ## API GATEWAY -> http://patient-service:4000/v3/api-docs
          - id: api-docs-patient-route
            uri: http://patient-service:4000
            predicates:
              - Path=/api/patients
            filters:
              - RewritePath=/api-docs/patients,/v3/api-docs


